[build]
default-target = "mips-unknown-linux-musl"

[target.mips-unknown-linux-musl]
build-std = ["std", "panic_abort"]
image = "ghcr.io/cross-rs/mips-unknown-linux-musl:main"

[target.aarch64-unknown-linux-gnu]
build-std = ["std", "panic_abort"]
#pre-build = [
#  "dpkg --add-architecture $CROSS_DEB_ARCH",
#  "apt-get update && apt-get install --assume-yes libssl3:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH",
#]
