//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "devicemetrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"oid\")")]
    pub msg_id: String,
    #[sea_orm(column_type = "custom(\"oid\")")]
    pub node_id: String,
    pub time: DateTime,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub battery_levels: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub voltage: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub channelutil: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub airutil: Option<f32>,
    pub latitude: Option<i32>,
    pub longitude: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub longname: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shortname: Option<String>,
    pub hwmodel: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nodeinfo::Entity",
        from = "Column::NodeId",
        to = "super::nodeinfo::Column::NodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Nodeinfo,
}

impl Related<super::nodeinfo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nodeinfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
