//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "environmentmetrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"oid\")")]
    pub msg_id: String,
    #[sea_orm(column_type = "custom(\"oid\")")]
    pub node_id: String,
    pub time: DateTime,
    #[sea_orm(column_type = "Float", nullable)]
    pub tempurature: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub relative_humidity: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub barometric_pressure: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub gas_resistance: Option<f32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub iaq: Option<String>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub wind_direction: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub wind_speed: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub wind_gust: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub wind_lull: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub rainfall_1h: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub rainfall_24h: Option<f32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nodeinfo::Entity",
        from = "Column::NodeId",
        to = "super::nodeinfo::Column::NodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Nodeinfo,
}

impl Related<super::nodeinfo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nodeinfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
