//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "localstats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"oid\")")]
    pub msg_id: u32,
    #[sea_orm(column_type = "custom(\"oid\")")]
    pub node_id: u32,
    pub time: NaiveDateTime,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub uptime_seconds: Option<u32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub channel_util: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub air_util_tx: Option<f32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_packets_tx: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_packets_rx: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_packets_rx_bad: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_online_nodes: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_total_nodes: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_rx_dupe: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_tx_relay: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_tx_relay_canceled: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nodeinfo::Entity",
        from = "Column::NodeId",
        to = "super::nodeinfo::Column::NodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Nodeinfo,
}

impl Related<super::nodeinfo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nodeinfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
