//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::prelude::Nodeinfo;
use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "errormetrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"oid\")")]
    pub msg_id: u32,
    #[sea_orm(column_type = "custom(\"oid\")")]
    pub node_id: u32,
    pub time: NaiveDateTime,
    #[sea_orm(column_type = "Float", nullable)]
    pub collision_rate: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub node_reach: Option<f32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub num_nodes: Option<u32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub usefulness: Option<f32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub avg_delay: Option<u32>,
    #[sea_orm(column_type = "custom(\"oid\")", nullable)]
    pub period: Option<u32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub errors: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nodeinfo::Entity",
        from = "Column::NodeId",
        to = "super::nodeinfo::Column::NodeId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Nodeinfo,
}

impl Related<Nodeinfo> for Entity {
    fn to() -> RelationDef {
        Relation::Nodeinfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
