//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

/// Prelude module which has common aliases
mod prelude;

/// Air quality metrics table
pub(crate) mod airqualitymetrics;
/// Device metrics table
pub(crate) mod devicemetrics;
/// Environment metrics table
pub(crate) mod environmentmetrics;
/// Local stats table
pub(crate) mod localstats;
/// Neighbor info table
pub(crate) mod neighborinfo;
/// Node info table
pub(crate) mod nodeinfo;
