//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

/// Air quality metrics entity alias
pub(super) use super::airqualitymetrics::Entity as Airqualitymetrics;
/// Device metrics entity alias
pub(super) use super::devicemetrics::Entity as Devicemetrics;
/// Environment metrics entity alias
pub(super) use super::environmentmetrics::Entity as Environmentmetrics;
/// Error metrics entity alias
pub(super) use super::errormetrics::Entity as ErrorMetrics;
/// Local stats entity alias
pub(super) use super::localstats::Entity as Localstats;
/// Neighbor info entity alias
pub(super) use super::neighborinfo::Entity as Neighborinfo;
/// Node info entity alias
pub(super) use super::nodeinfo::Entity as Nodeinfo;
